package common.assets;

public enum UserType {
    COMPANY_MANAGER,
    CUSTOMER,
    DALKAN,
    MARKETING_DEPARTMENT_WORKER,
    MARKETING_MANAGER,
    MARKETING_REPRESENTATIVE,
    STATION_MANAGER,
    SUPPLIER
}
